# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0.20
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: jwt_template
      MYSQL_ROOT_PASSWORD: jwt_template

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080